a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
addition=a+b
subtraction=a-b
print("addition=",addition)
print("subtraction=",subtraction)
multiplication=a*b
division=a/b
print("multiplication=",multiplication)
print("division=",division)